---
- hosts:
    - localhost
  vars:
    vfio_iommu: intel  # amd|intel
    vfio_pci_ids:
      - 10de:1d01
      - 10de:0fb8
      - 10de:1b06
      - 10de:10ef
      - 1b73:1100

    vfio_transparent_hugepage: false  # transparent_hugepage=never
    vfio_hugepages:  # First option is default
      - size: 1G
        count: 50

    vfio_hugetlbfs_group: hugetlbfs
    vfio_hugetlbfs_users:
      - xlevus
    vfio_hugetlbfs_mount: /hugepages

  roles:
    - vfio
    - libvirtd
