---

- name: Install python2-dnf
  become: yes
  package:
    state: present
    name: python2-dnf

- name: Add OVMF Repo
  become: yes
  yum_repository:
    file: firmware
    name: qemu-firmware-jenkins
    description: firmware for qemu, built by jenkins, fresh from git repos
    baseurl: https://www.kraxel.org/repos/jenkins/
    metadata_expire: 5m
    enabled: true
    gpgcheck: false
